package com.huy.chess.utils.enums

enum class TimeType {
    ONE_MINUTE,
    ONE_MINUTE_PLUS_ONE,
    TWO_MINUTES_PLUS_ONE,
    THREE_MINUTES,
    THREE_MINUTES_PLUS_TWO,
    FIVE_MINUTES,
    FIVE_MINUTES_PLUS_FIVE,
    FIVE_MINUTES_PLUS_TWO,
    TEN_MINUTES,
    TEN_MINUTES_PLUS_FIVE,
    FIFTEEN_MINUTES_PLUS_TEN,
    TWENTY_MINUTES,
    THIRTY_MINUTES,
    SIXTY_MINUTES,
    ONE_DAY,
    TWO_DAYS,
    THREE_DAYS,
    FIVE_DAYS,
    FOURTEEN_DAYS,
    UNLIMITED
}